### ISSUE TITLE
Silent option for http-server

### ISSUE THREAD

**Issue by OleksandrRakovets** [divhide/grunt-http-server#14]
Hi Oscar!

http-server has --silent CLI option to prevent printing requested files to console, while it's not yet available in the grunt task.

Could you please advise if it's possible to add this option to the task? I would like to submit a PR for it. Or do I need to go to http-server github?

Best,
Oleksandr.

**Comment by aetheon** [comment]
Their silent option is done by adding the ```logFn: requestLogger``` during the initialisation.
If you pass the ```logFn: null``` as an option you should get the silent behaviour.

But maybe its a good idea to add that option to this grunt plugin.

Let me know what you think and if that worked.

**Comment by OleksandrRakovets** [comment]
This have worked perfectly, many thanks! I would never guess this trick, so I believe the mirrored option from http-server readme will be more convenient.

**Comment by aetheon** [comment]
Gonna leave this opened to document that functionality.

**Comment by aetheon** [comment]
Documentation published with v1.4.
