### ISSUE TITLE
Allow usage of proxy connections

### ISSUE THREAD

**Issue by daredevil82** [divhide/grunt-http-server#17]
Nice wrapper for the `http-server` module.

However, the `http-server` module allows for proxy connections via the -P flag.  For example, a static frontend can be tested with a RESTy backend with

    http-server . -a 127.0.0.1 -p 443 -S -P http://127.0.0.1:8888

Nothing in the documentation for this plugin suggests this kind of capability.  If it does exist, how would it be used?

Thank you

**Comment by aetheon** [comment]
Hi @daredevil82,

I've just updated the README.md with the proxy instructions. Take a look and let me
know if its ok.

tks.

**Comment by daredevil82** [comment]
I appreciate the fast response! This will help a great deal.
